### ISSUE TITLE
Handler that removes itself

### ISSUE THREAD

**Issue by dbrgn** [rogierschouten/ts-events#10]
Maybe I missed it in the docs, but is there a way to create anonymous handlers that remove themselves? That would allow for "once" style handlers as well as handlers that need to disable themselves if a certain condition is met.

This is already possible by creating an explicit handler object and then attaching that to an event. However, when using an anonymous function or an arrow function, that doesn't seem to be possible.

**Comment by rogierschouten** [comment]
I don't think I implemented that but I could have a look at it end of next
week. Or you could send a PR maybe? I think it would be good to have.

**Comment by dbrgn** [comment]
Well, it depends on how you would design such a functionality. Many systems use a boolean return flag from the handler to denote whether the handler should be removed or not. But I don't know the codebase well enough to judge whether that would be a good option or not. Maybe another option would be to pass in an additional parameter to the handler, which could be called to disable itself. But I don't know how well that plays with the type system.

Very nice library otherwise, thanks! :)

**Comment by rogierschouten** [comment]
A return value isn't possible as handlers currently already (optionally) return a promise.   How about passing a 'once' option to the attach methods?

**Comment by rogierschouten** [comment]
I've implemented your request in version 3.2.0.   

I've added a once() method next to attach(), and AnyEvent#onceSync(), AnyEvent#onceQueued() and AnyEvent#onceAsync() next to their attachXXX() counterparts.

This way, it looks like EventEmitter#once().

I hope this helps, if not please let me know.

**Comment by dbrgn** [comment]
Really cool, thanks @rogierschouten! I'll let you know if I run into problems.
