### ISSUE TITLE
index.d.ts is missing in repo

### ISSUE THREAD

**Issue by episage** [rogierschouten/ts-events#2]
(4,1): error TS6053: File '<...>/node_modules/ts-events/typings/index.d.ts' not found.

It makes the package unusable :(

**Comment by episage** [comment]
See https://github.com/rogierschouten/ts-events/pull/3

**Comment by rogierschouten** [comment]
Should be fixed in ts-events@2.1.0 (I changed the version number from 3.0.0 to 2.1.0 in accordance with semver as there doesn't seem to be a breaking change). Thank you for your contribution!
