### ISSUE TITLE
How to obtain the d.t.s file in 2.3.0 ?

### ISSUE THREAD

**Issue by hnb2** [rogierschouten/ts-events#4]
Hi,

I have been using your library in version 2.0.0 for about 2 weeks, and I saw this morning that you upgraded to version 2.3.0. Everything seems fine except that I cannot find the declaration file.

Here is how I use ts-events :

``` ts
/// <reference path="../../vendor/jspm_packages/npm/ts-events@2.0.0/ts-events.d.ts" />
import {SyncEvent} from "ts-events";
```

Is there a new way to obtain it ?

**Comment by rogierschouten** [comment]
Typescript should now automatically take the dist/index.d.ts file so you
should be able to remove the reference to ts-events.d.ts .

**Comment by hnb2** [comment]
I see that you added a "typings" key in [package.json](https://github.com/rogierschouten/ts-events/blob/master/package.json#L15), but the dist/ directory is not indexed in git.

**Comment by rogierschouten** [comment]
That is correct. The Javascript output is in NPM only, not in Git

**Comment by rogierschouten** [comment]
Oh dear, I see that the latest version doesn't work at all after publishing to NPM.  It worked when I 'npm link'ed it to a test module. I'll revert and publish the old version under a new number so everyone can continue. Thanks for reporting.

**Comment by rogierschouten** [comment]
v2.4.0 published on NPM, all changes reverted. I hope it works for you, otherwise please just clamp your version to 2.0.0 in the meantime. I'm out for the day.

**Comment by hnb2** [comment]
Ok, i'll just clamp my version to 2.0.0 for now. Thanks for your quick answers !

**Comment by rogierschouten** [comment]
Version 3.0.0 is out and should work. @hnb2 can you please try and report back? Thanks!
