### ISSUE TITLE
Add dist/ + d.ts to the repo

### ISSUE THREAD

**Issue by RobinBuschmann** [rogierschouten/ts-events#5]
Hey, I really like the ts-events-module, but it can't be used out of the box, since it has no compiled files in it. I would recommend to add the dist/ folder including the d.ts-files to the repo. What do you think? Thanks in advance.

**Comment by rogierschouten** [comment]
Hi @RobinBuschmann I'd be happy to fulfill your use case.  Currently, the JavaScript output and .d.ts files are published on NPM so it's usable if you use commonjs and NPM. What would you like me to add? Browserified UMD module?  How would you like to use it?

**Comment by RobinBuschmann** [comment]
Ah ok. Thanks. I didn't know of that. I saw the repo without any compiled files and I had no idea, that a build can be configured for publishing on npm. I'm currently using jspm as a package manager. I've installed ts-events via `jspm install github:rogierschouten/ts-events`. When doing this, you'll got no compiled files, but `jspm install npm:ts-events` do the trick ;)

Another issue is the use of the node modules `assert` and `util` for ts-events. This prevents ts-events from using it in a browser. Despite of the fact that assert and util are not really essentially in ts-events, or am I wrong? What do you think?

**Comment by rogierschouten** [comment]
We use ts-events in the browser. We use a tool called 'browserify' for that.

**Comment by rogierschouten** [comment]
In v3.1.1 I've removed the dependencies on util and assert.  Next to that, I've also added ready-made UMD browser bundles.  I hope this makes it work for you, if not please feel free to post something again.  Thank you for letting me know!
