### ISSUE TITLE
Structure of the .d.ts file

### ISSUE THREAD

**Issue by hnb2** [rogierschouten/ts-events#7]
Hi there,

I just updated my project to Typescript 1.8.5 and I upgraded ts-events from 2.0.0 to 3.1.1 at the same time. But I have a problem with the declaration file.

In the [version 2.0.0](https://github.com/rogierschouten/ts-events/blob/v2.0.0/ts-events.d.ts) you used to 'wrap' the exports in a declare module. But in version 3.1.1 (npm only), you do not, and it is breaking my current implementation.

I made it work by manually modifying `vendor/jspm_packages/npm/ts-events@3.1.1/dist/lib/index.d.ts` to:

``` ts
declare module "ts-events" {
    export * from 'base-event';
    export * from 'sync-event';
    export * from 'queued-event';
    export * from 'async-event';
    export * from 'any-event';
    import { default as EventQueue } from 'EventQueue';
    export { default as EventQueue } from 'EventQueue';
    /**
     * The global event queue for QueuedEvents
     */
    export function queue(): EventQueue;
    /**
     * Convenience function, same as EventQueue.global().flushOnce().
     * Flushes the QueuedEvents, calling all events currently in the queue but not
     * any events put into the queue as a result of the flush.
     */
    export function flushOnce(): void;
    /**
     * Convenience function, same as EventQueue.global().flush().
     * Flushes the QueuedEvents, calling all handlers currently in the queue and those
     * put into the queue as a result of the flush.
     * @param maxRounds Optional, default 10. Number of iterations after which to throw an error because
     *                  the queue keeps filling up. Set to undefined or null to disable this.
     */
    export function flush(maxRounds?: number): void;
}
```

Which basically wraps up everything in a module, just like 2.0.0.

I use _JSPM_ to handle dependencies, and _typings_ to handle external module definitions (if available). At the top of my entry file I write:

``` ts
+/// <reference path="../typings/browser.d.ts" />
+/// <reference path="../vendor/jspm_packages/npm/ts-events@3.1.1/dist/lib/index.d.ts" />
```

Am I doing something wrong ? Thanks for your input.

**Comment by rogierschouten** [comment]
I'm so sorry, this issue has escaped my attention completely. I'm assuming this is no longer a problem for you. If it is, let me know.
